<?php
namespace JulianSeymour\PHPWebApplicationFramework\command;

use JulianSeymour\PHPWebApplicationFramework\common\AllocationModeInterface;

/**
 * A value-returning command that can be evaluated server side to return an array of nodes
 *
 * @author j
 */
interface NodeBearingCommandInterface extends IncrementVariableNameInterface, AllocationModeInterface, ValueReturningCommandInterface
{

	/**
	 * return true if nodes should be extracted from this command server side even when generating template function
	 */
	public static function extractAnyway();

	/**
	 * returns an array of nodes generated by evaluating this command
	 */
	public function extractChildNodes(int $mode): ?array;
}
